### ISSUE TITLE
Ready for checking 

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/PhaseUnwrapping_book#1]
Hi guys, 

Finished reproducing the last figure! 
I tried not to change their code as much as possible. I did this cool trick:

-  Using string concatenation (in *Julia*)  save several nifti files that contain the slices 

` output_nii_file = "data/output"*string(i)*".nii";`
    `julia_main(..,Int64(i),..);`

for every slice **i** in the main image. <br> 
This code saves them in multiple nifti files, where each file contains one slice that is filtered. 

- Load nifi files and then with list comprehensions (in *Python*) and **np.concatenate()** -> recreate this new nifti file that will contain all of the filtered slices

`# Load nifti files `
`nii_left = nib.load('partiallyUnwrappedMap.nii').get_fdata()`
`nii_list = [nib.load(f"output{i}.nii").get_fdata() for i in range(1,10)]`

`# Concatenate files using list comprehension, along adequate axis`
`newmap = [np.concatenate((nii[:,:,i], nii_left[:,:,i]), axis = 0) for i,nii in enumerate(nii_list)]`

- Load **newmap** with Plotly and toggle slices 

**Bonus**
Also I added: 

- really nice [feature](https://jupyterbook.org/content/layout.html) from the older Jupyter Book version (0.6.4) to display the figure in its **full width** 
- *(Click to expand plot code)* paragraph inside the built html to make the flow more readable 

Kiril

**Comment by mathieuboudreau** [comment]
Hi @zelenkastiot ,

Here is my review:

* [ ] I updated the introduction text in the branch `review_mb`, which I just opened an issue for. Please rebuild the book using this update and then merge.
* [ ] There's a need to distinguish the authors original github repository. I think you should link to that one under "GitHub Repository", or have a second one that links to "Original Code".
* [ ] Remove the "Theory Section", since it comes from the paper. When we reach out to the authors, we can ask if they want to write an explanation.
* [ ] In the figure, please add labels on top of the left and right figures to be `Prelude` and `Filtered`.
* [ ] On top of the scale bar, I think it should actually be be (`B<sub>0</sub> (Hz)`) and not (`FA (deg)`)
* [ ] In the Jupiter Notebook,  remove the output of the slices cell.
*[ ]  In the Jupyter Notebook, the link to `(from this fetched from repo)` points to the wrong github repository (it points to Zaki's).

Thanks!

Mathieu

**Comment by zelenkastiot** [comment]
Hi @mathieuboudreau , 

I modified everything on the review list! 

Regarding  the "Original Code" / "GitHub Repository" debate we had earlier, I added their original [repository ](https://github.com/nankueichen/Fourier_space_phase_unwrapping)as the link. 

Please let me know if everything is okay.
 
Kiril
